version: "3.7"
services:
  technical-documentation:
    build:
      context: ../frontend/static/technical-documentation
      dockerfile: technical-documentation.Dockerfile
    container_name: technical-documentation
    depends_on:
      - proxy
    volumes:
      - ../frontend/static/technical-documentation/dist:/var/www/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.technical-documentation.entrypoints=web
      - traefik.http.routers.technical-documentation.entrypoints=websecure
      - traefik.http.routers.technical-documentation.tls.certresolver=myresolver
      # Services
      - traefik.http.services.technical-documentation.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.routers.technical-documentation.middlewares=test-compress
      # Compress Middleware
      - traefik.http.middlewares.test-compress.compress=true
      # Redirect Scheme HTTP -> HTTPS
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443