################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  debug: true
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
experimental:
  http3: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leresolver
    http3:
      advertisedPort: "443"
  # streaming:
  #   address: ":1704/udp"
  # tcpep:
  #   address: ":3179"
  # udpep:
  #   address: ":3179/udp"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: serban.paul.91@gmail.com 
      storage: acme.json
      httpChallenge:
        entryPoint: web
